name: ci

on: [push, pull_request]

jobs:
  rust:
    name: wasm_dep_analyzer-ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_INCREMENTAL: 0
      GH_ACTIONS: 1
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install rust
        uses: dsherret/rust-toolchain-file@v1

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install up Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: |
          cargo fmt -- --check
          deno fmt --check

      - name: Lint
        run: cargo clippy --all-features --all-targets -- -D clippy::all

      - name: Cargo Build
        run: cargo build --all-features --all-targets

      - name: Cargo Test
        run: cargo test --all-features --all-targets

      - name: Cargo publish
        if: |
          github.repository == 'denoland/wasm_dep_analyzer' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
